<a href="https://colab.research.google.com/github/nageshkulkarni7/PyTorch/blob/main/GradientBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import torch
import numpy as np

In [19]:
x=torch.randn(3,requires_grad=True)
x

tensor([ 0.7857,  0.1907, -0.0183], requires_grad=True)

In [20]:
#Add back function baased on arithmatic operation
y=x+3
print(y)

z=y*2
print(z)

#v=z.mean()
#print(v)

tensor([3.7857, 3.1907, 2.9818], grad_fn=<AddBackward0>)
tensor([7.5715, 6.3813, 5.9635], grad_fn=<MulBackward0>)


In [21]:
#v.backward()   #- will not work as applicable to scalar only
n=torch.tensor([0.1,1.2,0.3],dtype=torch.float32)
z.backward(n)
print(x.grad)

tensor([0.2000, 2.4000, 0.6000])


In [27]:
#to stop gradients from tracking
xx=torch.randn(3,requires_grad=True)
print(xx)


tensor([0.9769, 1.4238, 0.1389], requires_grad=True)


In [28]:
xx.requires_grad_(False)
print(xx)

tensor([0.9769, 1.4238, 0.1389])


In [30]:
xx=torch.randn(2,requires_grad=True)
with torch.no_grad():
  print(xx)

tensor([ 1.2808, -0.8318], requires_grad=True)


In [31]:
#xx.grad.zero

AttributeError: ignored