<a href="https://colab.research.google.com/github/nageshkulkarni7/PyTorch/blob/main/LinearRegression%20With%20Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn
import numpy as np

In [ ]:
#Tensors are N-Dimensional array
#Pytorch provide tesnor usage with diff operations for computing ,gradients tracking and scientific computing
#can make use of GPU's for fast processing
# Autograd package of pytorch provides forward computational graph and backpropagting through graph allow to compute gradients

In [6]:
#pytorch basics
a=torch.randn(2,2)
b=torch.zeros(2,2)
b
print(b.dtype)  #torch.float32 is default data type


torch.float32


In [7]:
c=torch.ones(2,2,dtype=torch.float16)
c

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)

In [9]:
#Tensor slicing example
d=torch.rand(5,3)
d
print(d[:,0])    #First row [0,:]

tensor([0.3256, 0.1451, 0.6848, 0.9891, 0.7593])


In [10]:
#Reshaping the tesnors
s=torch.rand(4,4)
print(s.shape)
newview=s.view(16)
newview
print(newview.shape)

torch.Size([4, 4])
torch.Size([16])


In [11]:
#Numpy to tensor conversion
a=np.ones(5)
t=torch.from_numpy(a)
print(t.dtype)

torch.float64


In [17]:
#Gradient computation 
x=torch.randn(3,requires_grad=True)
y=x+3
print(y)

z=y*2
print(z)

#v=z.mean()
#print(v)
n=torch.tensor([0.1,1.2,0.3],dtype=torch.float32)
z.backward(n)

print(x.grad)

tensor([1.7656, 2.9331, 2.1407], grad_fn=<AddBackward0>)
tensor([3.5313, 5.8663, 4.2814], grad_fn=<MulBackward0>)
tensor([0.2000, 2.4000, 0.6000])


In [18]:
x=torch.tensor([2,4,6,8],dtype=torch.float32)
y=torch.tensor([4,8,12,16],dtype=torch.float32)
x
y

tensor([ 4.,  8., 12., 16.])

In [19]:
w=torch.tensor(0.00,dtype=torch.float32,requires_grad=True)
w

tensor(0., requires_grad=True)

In [20]:
#Create Model
#Construct loss and optimizer
#training loop -- forward pass , backward pass , update weights
def forward(x):
  y= w * x
  return y

In [21]:
loss=nn.MSELoss()

In [22]:
learning_rate=0.01

In [23]:
optimizer=torch.optim.SGD([w],lr=learning_rate)

In [24]:
for epoch in range(10):

  #Predcited
  y_expected=forward(x)
  print ("Epoch ", epoch +y_expected)

  #calculate loss
  l=loss(y_expected,y)

  #backward pass
  l.backward()

  #update gradients
  optimizer.step()

  #Stop tracking gradients
  optimizer.zero_grad()


print ("output", forward(25))




Epoch  tensor([0., 0., 0., 0.], grad_fn=<AddBackward0>)
Epoch  tensor([ 3.4000,  5.8000,  8.2000, 10.6000], grad_fn=<AddBackward0>)
Epoch  tensor([ 5.3600,  8.7200, 12.0800, 15.4400], grad_fn=<AddBackward0>)
Epoch  tensor([ 6.7440, 10.4880, 14.2320, 17.9760], grad_fn=<AddBackward0>)
Epoch  tensor([ 7.8976, 11.7952, 15.6928, 19.5904], grad_fn=<AddBackward0>)
Epoch  tensor([ 8.9590, 12.9181, 16.8771, 20.8362], grad_fn=<AddBackward0>)
Epoch  tensor([ 9.9836, 13.9672, 17.9508, 21.9345], grad_fn=<AddBackward0>)
Epoch  tensor([10.9934, 14.9869, 18.9803, 22.9738], grad_fn=<AddBackward0>)
Epoch  tensor([11.9974, 15.9948, 19.9921, 23.9895], grad_fn=<AddBackward0>)
Epoch  tensor([12.9990, 16.9979, 20.9969, 24.9958], grad_fn=<AddBackward0>)
output tensor(49.9948, grad_fn=<MulBackward0>)
