<a href="https://colab.research.google.com/github/nageshkulkarni7/PyTorch/blob/main/PyTorchBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x=torch.rand(2,2) # Random Number

In [3]:
print(x)

tensor([[0.3687, 0.6916],
        [0.0463, 0.4894]])


In [5]:
print (torch.zeros(2,2)) #Ones

tensor([[0., 0.],
        [0., 0.]])


In [6]:
print(x.dtype) # Default data type

torch.float32


In [7]:
x= torch.tensor(1,dtype=torch.float16)
x

tensor(1., dtype=torch.float16)

Arithmatic Operation

In [10]:
a=torch.add(1,2)
print(a)

tensor(3)


In [13]:
x= torch.ones(1)
x.add_(2)
x

tensor([3.])

In [14]:
x=torch.ones(2,2)
x.mul_(2)
x

tensor([[2., 2.],
        [2., 2.]])

Slicing

In [18]:
z=torch.rand(5,3)
z


tensor([[0.8516, 0.1655, 0.6845],
        [0.9241, 0.4093, 0.7373],
        [0.3701, 0.8274, 0.0013],
        [0.0143, 0.2171, 0.8014],
        [0.9272, 0.3231, 0.6977]])

In [21]:
print(z[:,0])  # First Column

tensor([0.8516, 0.9241, 0.3701, 0.0143, 0.9272])


In [23]:
print("First Row",z[0,:])

First Row tensor([0.8516, 0.1655, 0.6845])


In [25]:
print("At Element",z[1,1].item())

At Element 0.4093227982521057


Shape & Reshape

In [28]:
s=torch.rand(4,4)
print(s.shape)

newview=s.view(16)
newview
print(newview.shape)

torch.Size([4, 4])
torch.Size([16])


In [32]:
# tensor to numpy
import numpy as np
t=torch.ones(5)
# convert to numpy
n=t.numpy()
print(n)
print(type(n))
# inplace function will update all tensor as tensor point same memor location in CPU

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [33]:
#numpy to tensor
a=np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [35]:
t=torch.from_numpy(a) # default data type is 64
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)